version: '3.8'

services:
  fastapi:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres # Set the PostgreSQL username
      POSTGRES_PASSWORD: 123 # Set the PostgreSQL password
      POSTGRES_DB: fastapi # Set the PostgreSQL database name
    ports:
      - "5433:5432"    # Map the PostgreSQL port to the host
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres